services:
  postgres:
    image: postgres:15
    container_name: epi-postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: EpiDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
